# Generated by Django 2.2.2 on 2019-06-18 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamesh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='joinrecord',
            name='one_record_primary_key',
        ),
        migrations.RemoveConstraint(
            model_name='joinrecord',
            name='one_related_record_primary_key',
        ),
        migrations.AddField(
            model_name='logicmodulemodel',
            name='lookup_field_name',
            field=models.SlugField(default='id', help_text="Name of the field in the model for detail methods, p.e.: 'id' or 'uuid'", max_length=64),
        ),
        migrations.AddField(
            model_name='relationship',
            name='key',
            field=models.SlugField(default='joined_records', help_text="The key in the response body, where the related object data will be saved into, p.e.: 'contact_relationship'.", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinrecord',
            name='join_records_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logicmodulemodel',
            name='endpoint',
            field=models.CharField(blank=True, help_text="Endpoint of the model with leading and trailing slashs, p.e.: '/siteprofiles/'", max_length=255),
        ),
        migrations.AlterField(
            model_name='logicmodulemodel',
            name='logic_module_model_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('record_id', None), ('record_uuid', None), _negated=True), models.Q(models.Q(_negated=True, record_id=None), models.Q(_negated=True, record_uuid=None), _negated=True)), name='one_record_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('related_record_id', None), ('related_record_uuid', None), _negated=True), models.Q(models.Q(_negated=True, related_record_id=None), models.Q(_negated=True, related_record_uuid=None), _negated=True)), name='one_related_record_primary_key'),
        ),
    ]
