# Generated by Django 2.2.2 on 2019-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamesh', '0002_auto_20190618_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('record_uuid', None), ('related_record_uuid', None)), fields=('relationship', 'record_id', 'related_record_id'), name='unique_join_record_ids'),
        ),
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('record_id', None), ('related_record_id', None)), fields=('relationship', 'record_uuid', 'related_record_uuid'), name='unique_join_record_uuids'),
        ),
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('record_uuid', None), ('related_record_id', None)), fields=('relationship', 'record_id', 'related_record_uuid'), name='unique_join_record_id_uuid'),
        ),
        migrations.AddConstraint(
            model_name='joinrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('record_id', None), ('related_record_uuid', None)), fields=('relationship', 'record_uuid', 'related_record_id'), name='unique_join_record_uuid_id'),
        ),
    ]
