# Generated by Django 2.2.13 on 2022-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamesh', '0003_auto_20220117_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='origin_fk_field_name',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='origin_lookup_field_name',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='related_fk_field_name',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='related_lookup_field_name',
        ),
        migrations.AddField(
            model_name='relationship',
            name='fk_field_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
