# Generated by Django 2.2.3 on 2019-07-15 09:24

from django.db import migrations


def set_logic_module_endpoint_name(apps, schema_editor):
    LogicModuleModel = apps.get_model('datamesh', 'LogicModuleModel')
    for lmm in LogicModuleModel.objects.all():
        lmm.logic_module_endpoint_name = lmm.logic_module.endpoint_name
        lmm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamesh', '0005_auto_20190715_0906'),
    ]

    operations = [
        migrations.RunPython(set_logic_module_endpoint_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='logicmodulemodel',
            name='logic_module',
        ),
    ]
