# Generated by Django 2.2.3 on 2019-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamesh', '0006_remove_logicmodulemodel_logic_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logicmodulemodel',
            unique_together={('logic_module_endpoint_name', 'endpoint'), ('logic_module_endpoint_name', 'model')},
        ),
    ]
