# Generated by Django 2.2.3 on 2019-07-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamesh', '0007_auto_20190715_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrecord',
            old_name='join_records_uuid',
            new_name='join_record_uuid',
        ),
    ]
