# Generated by Django 2.2.10 on 2021-06-28 15:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consortium',
        ),
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('consortium_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Consortium UUID')),
                ('name', models.CharField(blank=True, help_text='Multiple organizations form a consortium together', max_length=255, verbose_name='Consortium Name')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('custodian_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custodian UUIDs'), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'Consortiums',
                'ordering': ('name',),
            },
        ),
    ]
