# Generated by Django 2.2.9 on 2020-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicmodule',
            old_name='relationships',
            new_name='api_specification',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, help_text='Each end user must be grouped into an organization', max_length=255, verbose_name='Organization Name'),
        ),
    ]
