# Generated by Django 5.0.14 on 2025-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coregroup_id_alter_coresites_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicmodule',
            name='swagger_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
