# Generated by Django 2.2.10 on 2021-07-07 07:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.migrations.operations.special



def migrate_email_alert(apps, schema_editor):
    CoreUser = apps.get_model("core","CoreUser")
    for record in CoreUser.objects.all():
        record.email_preferences = {'environmental': record.email_alert_flag}
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consortium'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='email_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='push_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='user_timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_email_alert,migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='coreuser',
            name='email_alert_flag',
        ),
    ]
