# Generated by Django 2.2.10 on 2021-07-12 06:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coreuser_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consortium',
            name='custodian_uuids',
        ),
        migrations.AddField(
            model_name='consortium',
            name='organization_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization UUIDs'), blank=True, null=True, size=None),
        ),
    ]
