# Generated by Django 2.2.10 on 2021-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coreuser_email_alert_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_import_export',
            field=models.BooleanField(default=False, verbose_name='To allow import export functionality'),
        ),
    ]
