# Generated by Django 2.2.27 on 2022-05-05 08:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220203_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
