# Generated by Django 2.2.10 on 2021-07-20 05:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210712_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consortium',
            name='organization_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True, null=True, verbose_name='Organization UUIDs'), blank=True, null=True, size=None),
        ),
    ]
