# Generated by Django 2.2.10 on 2021-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_allow_import_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='radius',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
