# Generated by Django 2.2.10 on 2022-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210720_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='radius',
            field=models.FloatField(blank=True, default=0.0, max_length=20, null=True),
        ),
    ]
