# Generated by Django 2.2.27 on 2022-06-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_stripe_subscription_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Product Team', 'Product Team')], default='Product Team', max_length=50, null=True),
        ),
    ]
