# Generated by Django 2.2.28 on 2022-09-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220620_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stripe_subscription_details',
        ),
    ]
