# Generated by Django 2.2.28 on 2022-08-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220620_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partners'},
        ),
    ]
