# Generated by Django 3.2.24 on 2024-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220823_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
