# Generated by Django 2.2.28 on 2022-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_organization_stripe_subscription_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='unlimited_free_plan',
            field=models.BooleanField(default=True, verbose_name='Free unlimited features plan'),
        ),
    ]
