# Generated by Django 2.2.10 on 2021-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtype',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
