# Generated by Django 2.2.28 on 2023-01-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230115_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stripe_info',
        ),
    ]
