# Generated by Django 2.2.28 on 2023-01-15 15:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_organization_stripe_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='card',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_card_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_by',
            field=models.ForeignKey(blank=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscription', to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
