# Generated by Django 2.2.28 on 2023-02-15 14:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230207_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_product_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
