# Generated by Django 2.2.28 on 2023-03-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coreuser_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreuser',
            old_name='coupon',
            new_name='coupon_code',
        ),
    ]
