# Generated by Django 2.2.28 on 2023-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_card_id',
            new_name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer_stripe_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
