# Generated by Django 2.2.28 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230319_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
