# Generated by Django 2.2.28 on 2024-08-20 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240630_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('duration', models.CharField(choices=[('forever', 'Forever'), ('once', 'Once'), ('repeating', 'Repeating')], default='once', max_length=16)),
                ('duration_in_months', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('max_redemptions', models.IntegerField(default=1)),
                ('percent_off', models.FloatField(default=0)),
                ('amount_off', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('stripe_coupon_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-create_date'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_subscription', to='core.Coupon'),
        ),
    ]
