# Generated by Django 2.2.28 on 2024-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240828_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
