# Generated by Django 2.2.4 on 2019-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicmodule',
            name='docs_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
