# Generated by Django 2.0.7 on 2019-01-23 15:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicmodule',
            name='github_repo',
        ),
        migrations.AddField(
            model_name='logicmodule',
            name='relationships',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
