# Generated by Django 2.0.7 on 2019-04-15 14:56
import re

from django.db import migrations, models


def set_endpoint_name(apps, schema_editor):
    LogicModule = apps.get_model('gateway', 'LogicModule')
    for logic_module in LogicModule.objects.all():
        module_name = re.sub('_service$', '', logic_module.name.lower())
        logic_module.endpoint_name = module_name
        logic_module.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20190123_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicmodule',
            name='endpoint_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(set_endpoint_name),
        migrations.AlterUniqueTogether(
            name='logicmodule',
            unique_together={('endpoint', 'endpoint_name')},
        ),
    ]
