# Generated by Django 2.2.6 on 2019-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        ('gateway', '0002_logicmodule_docs_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicmodule',
            name='core_groups',
            field=models.ManyToManyField(blank=True, related_name='logic_module_set', related_query_name='logic_module', to='workflow.CoreGroup', verbose_name='Logic Module groups'),
        ),
    ]
