#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi

		# Check for WIP commit
		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
		if [ -n "$commit" ]
		then
			echo >&2 "pre-push hook: Found WIP commit in $local_ref, not pushing"
			echo >&2 "If you really want to do this, use --no-verify to bypass this pre-push hook."
			exit 1
		fi
	fi
done


branch=`git rev-parse --abbrev-ref HEAD`
push_command=`ps -ocommand= -p $PPID`
protected_branches=('master' 'demo' 'dev' 'staging')

is_protected_branch=`echo ${protected_branches[*]} | grep "$branch"`

if [[ "${is_protected_branch}" != "" && "$push_command" =~ force|delete|-f ]]; then
    if [ "$remote" == "origin" ]; then
        origin_url=`git remote get-url origin`
        if [ "$origin_url" != "git@github.com:humanitec/bifrost.git" ]; then
            exit 0
        fi
    fi

	echo >&2 "pre-push hook: Prevented force-push to $branch. This is a very dangerous command."
	echo >&2 "If you really want to do this, use --no-verify to bypass this pre-push hook."
	exit 1
fi


if [ "$remote" == "origin" ]; then
    origin_url=`git remote get-url origin`
    if [ "$origin_url" != "git@github.com:humanitec/bifrost.git" ]; then
        exit 0
    fi
fi


echo >&2 "pre-push hook: running flake8..."
docker-compose -f docker-compose-dev.yml run --entrypoint 'flake8 --exclude=settings,migrations' bifrost_api

if [[ $? -ne 0 ]]; then
    echo >&2 "pre-push hook: you have some error when passing flake8."
    echo >&2 "If you really want to do this, use --no-verify to bypass this pre-push hook."
    exit 1
fi

exit 0
