# Generated by Django 2.0.7 on 2018-10-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogicModule',
        ),
    ]
