# Generated by Django 2.0.7 on 2019-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coregroup',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='coregroup',
            old_name='core_group_uuid',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='core_groups',
            field=models.ManyToManyField(blank=True, related_name='workflowlevel1s', related_query_name='workflowlevel1s', to='workflow.CoreGroup', verbose_name='Core groups'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='core_groups',
            field=models.ManyToManyField(blank=True, related_name='workflowlevel2s', related_query_name='workflowlevel2s', to='workflow.CoreGroup', verbose_name='Core groups'),
        ),
        migrations.AlterField(
            model_name='coregroup',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name of the role'),
        ),
        migrations.RemoveField(
            model_name='coregroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='coregroup',
            name='permissions',
            field=models.PositiveSmallIntegerField(default=4, help_text='Decimal integer from 0 to 15 converted from 4-bit binary, each bit indicates permissions for CRUD', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='coregroup',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='coregroup',
            name='organization',
        ),
    ]
