# Generated by Django 2.0.7 on 2019-03-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coregroup',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='coregroup',
            old_name='core_group_uuid',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='coregroup',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='coregroup',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2'),
        ),
        migrations.AlterField(
            model_name='coregroup',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name of the role'),
        ),
        migrations.RemoveField(
            model_name='coregroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='coregroup',
            name='permissions',
            field=models.PositiveSmallIntegerField(default=15, help_text='Decimal integer from 0 to 15 converted from 4-bit binary, each bit indicates permissions for CRUD', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='coregroup',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='coregroup',
            name='organization',
        ),
    ]
