# Generated by Django 2.0.7 on 2018-12-20 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_delete_logicmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowteam',
            name='team_uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True, verbose_name='WorkflowLevel1 UUID'),
        ),
    ]
