# Generated by Django 2.0.7 on 2019-04-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190402_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='workflowlevel1',
        ),
        migrations.DeleteModel(
            name='HistoricalWorkflowLevel2',
        ),
    ]
