# Generated by Django 2.0.7 on 2019-01-29 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190123_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Token')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization', verbose_name='Organization')),
            ],
        ),
    ]
