# Generated by Django 2.0.7 on 2019-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190402_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='coregroup',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is organization default group'),
        ),
    ]
