# Generated by Django 2.0.7 on 2019-02-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190123_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Password resetting'), (2, 'Invitation')], verbose_name='Type of template')),
                ('template', models.TextField(blank=True, null=True, verbose_name='Reset password e-mail template (text)')),
                ('template_html', models.TextField(blank=True, null=True, verbose_name='Reset password e-mail template (HTML)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('organization', 'type')},
        ),
    ]
