# Generated by Django 2.0.7 on 2019-02-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190123_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkflowlevel2',
            old_name='level2_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='workflowlevel2',
            old_name='level2_uuid',
            new_name='uuid',
        ),
    ]
