# Generated by Django 2.0.7 on 2019-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190123_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reset_password_tpl',
            field=models.TextField(blank=True, null=True, verbose_name='Reset password e-mail template (text)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reset_password_tpl_html',
            field=models.TextField(blank=True, null=True, verbose_name='Reset password e-mail template (HTML)'),
        ),
    ]
