# Generated by Django 2.0.7 on 2019-05-14 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_coregroup_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLevelType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of workflow2 type', max_length=255, verbose_name='Name')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowlevel2s', to='workflow.WorkflowLevelType'),
        ),
    ]
