# Generated by Django 2.0.7 on 2019-03-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20190226_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
