# Generated by Django 2.0.7 on 2019-03-07 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('workflow', '0005_auto_20190226_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_group_uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='CoreGroup UUID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_groups', to='workflow.Organization')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Permissions')),
            ],
            options={
                'ordering': ('organization',),
            },
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('name',), 'verbose_name_plural': 'Industries'},
        ),
        migrations.AddField(
            model_name='coreuser',
            name='core_groups',
            field=models.ManyToManyField(blank=True, to='workflow.CoreGroup', verbose_name='Core Groups'),
        ),
        migrations.AlterUniqueTogether(
            name='coregroup',
            unique_together={('name', 'organization')},
        ),
    ]
