# Generated by Django 2.0.7 on 2019-02-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20190212_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowlevel1',
            old_name='level1_uuid',
            new_name='uuid',
        ),
    ]
