# Generated by Django 2.0.7 on 2019-03-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20190304_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coregroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_groups', to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='coregroup',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_groups', to='workflow.WorkflowLevel1'),
        ),
    ]
