# Generated by Django 2.2.1 on 2019-05-27 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20190527_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel2',
            name='level2_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=False, editable=False, help_text='Unique ID', unique=True, verbose_name='WorkflowLevel2 UUID'),
        ),
    ]
