# Generated by Django 2.0.7 on 2019-03-14 10:07

from django.db import migrations
from django.contrib.auth.models import Group


def forwards(apps, schema_editor):
    Group.objects.filter(name='ProgramAdmin').update(name='WorkflowAdmin')
    Group.objects.filter(name='ProgramTeam').update(name='WorkflowTeam')


def backwards(apps, schema_editor):
    Group.objects.filter(name='WorkflowAdmin').update(name='ProgramAdmin')
    Group.objects.filter(name='WorkflowTeam').update(name='ProgramTeam')


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20190313_1016'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
