# Generated by Django 2.0.7 on 2019-03-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20190305_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='coregroup',
            name='role',
            field=models.CharField(blank=True, choices=[('OrgAdmin', 'OrgAdmin'), ('ViewOnly', 'ViewOnly'), ('WorkflowAdmin', 'WorkflowAdmin'), ('WorkflowTeam', 'WorkflowTeam')], max_length=255, null=True, verbose_name='Role'),
        ),
    ]
