# Generated by Django 2.0.7 on 2019-03-13 17:20

import uuid
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('workflow', '0008_change_group_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreuser',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelManagers(
            name='coreuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='core_groups',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='workflow.CoreGroup', verbose_name='User groups'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coreuser',
            name='roles',
            field=models.CharField(blank=True, choices=[('OrgAdmin', 'OrgAdmin'), ('WorkflowAdmin', 'WorkflowAdmin'), ('WorkflowTeam', 'WorkflowTeam'), ('ViewOnly', 'ViewOnly')], max_length=100, null=True, verbose_name='User roles'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', related_query_name='core_user', to='auth.Permission', verbose_name='User permissions'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='username',
            field=models.CharField(default=uuid.uuid4, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
