# Generated by Django 2.0.7 on 2019-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20190313_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
