# Generated by Django 2.2.1 on 2019-05-27 13:23

from django.db import migrations, models
import uuid

core_group_wfl2_map = {}


def forward_read_workflowlevel2_core_groups(apps, schema_editor):
    """Save relations to local variable."""
    core_group_model = apps.get_model('workflow', 'CoreGroup')
    db_alias = schema_editor.connection.alias
    core_groups = core_group_model.objects.using(db_alias).all()
    for core_group in core_groups:
        core_group_wfl2_map[core_group.pk] = list(core_group.workflowlevel2s.values_list('level2_uuid', flat=True))
    print(core_group_wfl2_map)


def forward_save_workflowlevel2_core_groups(apps, schema_editor):
    """Read relations from local variable and save."""
    wfl2_model = apps.get_model('workflow', 'WorkflowLevel2')
    db_alias = schema_editor.connection.alias
    for core_group_pk, wfl2_array in core_group_wfl2_map.items():
        for wfl2_uuid in wfl2_array:
            wfl2_model.objects.using(db_alias).get(pk=wfl2_uuid).core_groups.add(core_group_pk)


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20190527_1321'),
    ]

    operations = [
        migrations.RunPython(forward_read_workflowlevel2_core_groups,
                             migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='id',
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='level2_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='core_groups',
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='core_groups',
            field=models.ManyToManyField(blank=True, related_name='workflowlevel2s',
                                         related_query_name='workflowlevel2s', to='workflow.CoreGroup',
                                         verbose_name='Core groups'),
        ),
        migrations.RunPython(forward_save_workflowlevel2_core_groups,
                             migrations.RunPython.noop),
    ]
