# Generated by Django 2.0.7 on 2019-05-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_level2_uuid_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowlevel2sort',
            options={'ordering': ('workflowlevel1', 'workflowlevel2_pk'), 'verbose_name': 'Workflow Level Sort', 'verbose_name_plural': 'Workflow Level Sort'},
        ),
        migrations.RemoveField(
            model_name='workflowlevel2sort',
            name='workflowlevel2_id',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2sort',
            name='workflowlevel2_parent_id',
        ),
        migrations.AddField(
            model_name='workflowlevel2sort',
            name='workflowlevel2_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2'),
        ),
        migrations.AddField(
            model_name='workflowlevel2sort',
            name='workflowlevel2_pk',
            field=models.UUIDField(default='00000000-0000-4000-8000-000000000000', verbose_name='UUID to be Sorted'),
        ),
    ]
