# Generated by Django 2.0.7 on 2019-03-14 09:51

from django.db import migrations
from workflow.models import CoreUser


def forwards(apps, schema_editor):
    for core_user in CoreUser.objects.all():
        user = core_user.user
        core_user.username = user.username
        core_user.first_name = user.first_name
        core_user.last_name = user.last_name
        core_user.email = user.email
        core_user.is_staff = user.is_staff
        core_user.is_active = user.is_active
        core_user.is_superuser = user.is_superuser
        core_user.last_login = user.last_login
        core_user.password = user.password
        core_user.date_joined = user.date_joined

        core_user.user_permissions.add(*list(user.user_permissions.all()))

        for role in user.groups.all():
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_coreuser_is_active'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
