# Generated by Django 2.0.7 on 2019-05-31 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20190528_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Organization UUID'),
        ),
    ]
