# Generated by Django 2.0.7 on 2019-03-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_migrate_data_from_user_to_coreuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OrgAdmin', 'OrgAdmin'), ('WorkflowAdmin', 'WorkflowAdmin'), ('WorkflowTeam', 'WorkflowTeam'), ('ViewOnly', 'ViewOnly')], max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='workflow.Role', verbose_name='User roles'),
        ),
    ]
