# Generated by Django 2.0.7 on 2019-05-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20190531_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_uuid',
            new_name='uuid',
        ),
    ]
