# Generated by Django 2.0.7 on 2019-03-14 13:51

from django.db import migrations
from django.contrib.auth.models import Group
from workflow.models import CoreUser, Role


def forwards(apps, schema_editor):
    for group in Group.objects.all():
        Role.objects.create(name=group.name)

    for core_user in CoreUser.objects.all():
        roles = Role.objects.filter(name__in=core_user.groups.values_list('name', flat=True))
        core_user.roles.add(*list(roles))


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20190314_1254'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
