# Generated by Django 2.0.7 on 2019-03-14 13:51

from django.db import migrations
from django.contrib.auth.models import Group
from workflow.models import CoreUser, Role


def forwards(apps, schema_editor):
    for group in Group.objects.all():
        Role.objects.get_or_create(name=group.name)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20190314_1254'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
