# Generated by Django 2.0.7 on 2019-06-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_org_uuid_pk_with_fks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='uuid',
            new_name='organization_uuid',
        ),
    ]
