# Generated by Django 2.2.3 on 2019-07-31 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_rename_org_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLevelStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(help_text='Name of WorkflowLevelStatus', max_length=255, verbose_name='Name')),
                ('short_name', models.SlugField(max_length=63, unique=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Level Status',
                'verbose_name_plural': 'Workflow Level Statuses',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowlevel2s', to='workflow.WorkflowLevelStatus'),
        ),
    ]
