# Generated by Django 2.0.7 on 2019-03-15 10:57

from django.db import migrations, connection
from django.db.utils import ProgrammingError


def forwards(apps, schema_editor):
    sql = """
    UPDATE workflow_workflowlevel2 as wf2
    SET _created_by = cu.id
    FROM auth_user AS u
    INNER JOIN workflow_coreuser as cu ON cu.user_id = u.id
    WHERE wf2.created_by = u.id
    """
    try:
        with connection.cursor() as cursor:
            cursor.execute(sql)
    except ProgrammingError:
        pass


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20190315_1050'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
