# Generated by Django 2.2.3 on 2019-08-22 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_default_statuslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel2',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
