# Generated by Django 2.0.7 on 2019-03-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20190315_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='workflowlevel1',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='workflowlevel1',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='milestone',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
