# Generated by Django 2.2.3 on 2019-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20190822_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlevel2',
            name='project_id',
            field=models.IntegerField(blank=True, help_text='ID set by the customer. Must be unique in organization.', null=True),
        ),
        migrations.AddConstraint(
            model_name='workflowlevel2',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, project_id=None), fields=('workflowlevel1', 'project_id'), name='unique_workflowlevel1_project_id'),
        ),
    ]
