# Generated by Django 2.0.7 on 2019-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20190315_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='core_groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='workflow.CoreGroup', verbose_name='User groups'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
